apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image: dhrbduf/register-app-pipeline:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
